### ISSUE TITLE
Document README.txt

### ISSUE THREAD

**Issue by pythagoraswitch** [worldbank/cv4ag#3]
+ How to set this up (docker etc)
+ How to contribute
+ License
+ Acknowledgement of previous work (If we use skynet/segnet)
+ Some pictures of output would be nice!

**Comment by hep-ml** [comment]
Will be done.

**Comment by pythagoraswitch** [comment]
+ explain what it does (data processing part and training part)

**Comment by hep-ml** [comment]
See `https://github.com/worldbank/cv4ag/blob/master/documentation/report_cv4ag.tex` (has to be compiled via `pdflatex` and `bibtex`
